### ISSUE TITLE
deepseek does not change to gpt4

### ISSUE THREAD

**Issue by legaltextai** [rainchen/dify-tool-LongTermMemory#1]
thanks for this tool! i 've changed to gpt4 but it still requires deepseek credentials? 
<img width="1663" alt="Screenshot 2024-07-03 at 8 50 42 AM" src="https://github.com/rainchen/dify-tool-LongTermMemory/assets/144342123/f893181e-cce2-45ac-8fa4-245cbddaf5b6">

**Comment by legaltextai** [comment]
never mind , fixed it. forgot to change llm in the workflow tool. thank you so much!!!

**Comment by rainchen** [comment]
I added more notes in README about this config. Looking forward more feedbacks.
