### ISSUE TITLE
So close to running, but getting strange errors. 

### ISSUE THREAD

**Issue by nickknyc** [rainchen/dify-tool-LongTermMemory#3]
Hi, I would really appreciate it if you could take a look at this and see were I am going wrong. 

I am running Dify in a Docker image hosted on a windows 11 machine

The rest of Dify seems to be running fine. I have also attached the yaml - which I made some changes to in desperation

Here is the error that stops me from running successfully
![image](https://github.com/user-attachments/assets/de1e0a89-78bd-4942-9956-9d101120bcd3)
![image](https://github.com/user-attachments/assets/68396c4f-9eb0-44e0-8060-235bbc99b6ff)
![image](https://github.com/user-attachments/assets/dd853085-e14e-4ec8-b548-0ddf835b9c59)
![image](https://github.com/user-attachments/assets/529c63ca-3bd5-470d-8b10-3cca00c17c04)
{
  "api_key": "app-Mi6cttOkXIX72eEN8NakjKzO",
  "base_url": "http://localhost/",
  "memory_template": "<UserInfo>   <name>${user_name}</name>   <age>${user_age}</age>   <hobbies>${user_hobbies}</hobbies>   <any_user_info>${any_user_info}</any_user_info> </UserInfo>",
  "dataset_id": "063f1f6c-bd21-46da-9bdb-7df2cfbb0d9d",
  "document_id": "cd59a597-a6b7-4a52-a503-ebd04935a4fa",
  "user_input": "asdas"
}

I get the same error with the app and the data api_keys
Also, I have tried many base url's - they seem to have no effect.

here is more 
![image](https://github.com/user-attachments/assets/e8c4398d-0bb6-416b-a11d-4e7001fc9ad9)
![image](https://github.com/user-attachments/assets/d2943d8b-5e2e-4fd8-af91-6c8fbb523cea)
![image](https://github.com/user-attachments/assets/9b4c49c0-b947-4d77-a529-d3e2bfa18518)
![image](https://github.com/user-attachments/assets/454f14fc-4ec9-45dc-a136-29094b55c02a)
![image](https://github.com/user-attachments/assets/2216502f-4356-418a-b6c3-f2ecfca0be7f)
![image](https://github.com/user-attachments/assets/84d6105e-cd6c-4529-a523-c7f206669310)
![image](https://github.com/user-attachments/assets/4ac68f2f-c968-4524-9b71-faafbfaab350)
![image](https://github.com/user-attachments/assets/7e2b6100-a9ff-47eb-aba4-7524b4866216)
[LongTermMemory.yml.txt](https://github.com/user-attachments/files/16446766/LongTermMemory.yml.txt)

Thanks so much - love the way you have this implemented..

**Comment by rainchen** [comment]
I don't have a Windows 11 env to test this issue.
You can try using `http://docker.for.win.localhost` for `base_url`
refs: https://stackoverflow.com/questions/40746453/how-to-connect-to-docker-host-from-container-on-windows-10-docker-for-windows/40789612#40789612
More: https://docs.docker.com/docker-for-windows/networking/

and `api_key` was wrong. It's Dify's Knowledge API key, not "Chat App API key".(maybe I should use the other name)
You can get it on 'Knowledge -> API ACCESS' page,  a Knowledge API key should be look like "dataset-xxx"

You can watch the demo video closely by pausing, as it has been sped up.

**Comment by nickknyc** [comment]
> I don't have a Windows 11 env to test this issue.
> You can try using `http://docker.for.win.localhost` for `base_url`
> refs: https://stackoverflow.com/questions/40746453/how-to-connect-to-docker-host-from-container-on-windows-10-docker-for-windows/40789612#40789612
> More: https://docs.docker.com/docker-for-windows/networking/
> 
> and `api_key` was wrong. It's Dify's Knowledge API key, not "Chat App API key".(maybe I should use the other name)
> You can get it on 'Knowledge -> API ACCESS' page,  a Knowledge API key should be look like "dataset-xxx"
> 
> You can watch the demo video closely by pausing, as it has been sped up.
> 
> 
> 

thank you so much! I'm doing a complete rebuild today and will try again. Super helpful links - i need to learn more about docker networking 🙄

**Comment by nickknyc** [comment]
AWESOME... am now up and running!! I did a complete reinstall of dify - then just followed your YouTube very very closely 
Thanks

**Comment by rainchen** [comment]
enjoy the fun 😉
