### ISSUE TITLE
记忆要套模版的话，是否意味着只能存特定的内容

### ISSUE THREAD

**Issue by daizy008** [rainchen/dify-tool-LongTermMemory#5]
如题。能不能像Mem0 一样，LLM先判断是否需要记忆呢

**Comment by rainchen** [comment]
原本的设计理念是想做到可以结构化存储开发者定义的任意信息，用于支撑需要做表单信息收集的应用场景，方便应用端可以通过Dify 知识库API读取对应知识库里的结构内容来解析使用。
记忆随意内容的话，感觉只能做对话助手之类的有用。有什么使用场景吗？

**Comment by rainchen** [comment]
Closed as there is no further feedback.
