### ISSUE TITLE
Do I need to install docker?

### ISSUE THREAD

**Issue by jorgearone** [rainchen/dify-tool-LongTermMemory#6]
Hello again,
I tell you that so far I have not been able to use it, it generates this doubt, the last time you told me that I did not need to install the docker that was enough the Dify cloud, however I can not understand thi
![asdfasdfddfd](https://github.com/user-attachments/assets/f7e54223-f51f-4b23-b180-079a02d100f4)
s direction.

**Comment by rainchen** [comment]
The idea is let the Dify Code Node to request Dify's Knowledge API(see https://docs.dify.ai/guides/knowledge-base/maintain-dataset-via-api)
So if you're using Dify Cloud, you should use cloud version API `https://api.dify.ai/` as the base_url parameter value.
If you're using "Deploy with Docker Compose" solution,  it dependents:
-  use `http://host.docker.internal` on MacOS/Linux
- use `http://docker.for.win.localhost`  on  Windows 10/11
- if you changed default nginx port config, append the port you used

**Comment by jorgearone** [comment]
Hi, I told you that I decided to create an instance in google VPS (https://github.com/futurminds/dify-self-hosted?tab=readme-ov-file)

but I'm getting an error?  initially I got an error, when I run it again, it keeps thinking.

any suggestions, maybe I have to enable a new port?

thanks for your help in advance. 🙌
![image](https://github.com/user-attachments/assets/9637ecb4-6a9e-4d56-9c6f-b282dc087dbb)

**Comment by jorgearone** [comment]
I finally decided to host in a vps. but I found it curious that it only works with the DeepSeek provider. When I used the same model through the Openrouter it gave me an error with the credentials. in the end I had to enable the provider directly, what do you think happened?

**Comment by rainchen** [comment]
Did you try creating a new chatbot using Openrouter provider and working fine?
The requirement for the LLM is that its performance must be equivalent to that of GPT-4 or DeepSeek. Should not be limited to the DeepSeek provider.

**Comment by jorgearone** [comment]
Hi rainchen 
I thought it was weird too, anyway.

I was wondering if you have tried to use it from the mobile, either (Telegram, Line or WhatsApp).
Any ideas on how to implement it? and which of the 3 apps would you recommend.

**Comment by rainchen** [comment]
> Hi rainchen I thought it was weird too, anyway.
> 
> I was wondering if you have tried to use it from the mobile, either (Telegram, Line or WhatsApp). Any ideas on how to implement it? and which of the 3 apps would you recommend.

I have no experiences with these apps.
