### ISSUE TITLE
Different behavior between Workflow Test and Chatbot (Workflow as Tool)

### ISSUE THREAD

**Issue by haruyo** [rainchen/dify-tool-LongTermMemory#7]
Hi, 
Thank you for creating this useful tool!

I'm using Dify cloud version with a PRO plan and encountered some issues with the implementation.

I made some modifications to make the workflow work, as the original code had some issues:

1. Modified JSON format:
For Add memory, changed to:
```json
{"segments":[{"content":"{{#1719907179295.longterm_memory_content#}}","keywords":["{{#sys.user_id#}}"]}]}
```

For Update memory, changed to:
```json
{"segment":{"content":"{{#1719907179295.longterm_memory_content#}}","keywords":["{{#sys.user_id#}}"]}}
```

2. Modified agent prompt by adding:
- Specific instructions for XML output format
- Clear example of escaping special characters: `user_id=\\\"[user_id]\\\"`
- Explicit instruction not to include line breaks
- Specification for JSON-compatible output format

Current issue:
- The workflow works fine in the Workflow Test
- However, when using it as a Chatbot (Workflow as Tool), it fails at Add memory node
- Error message: `Expecting ',' delimiter: line 1 column 30 (char 29)`

Could you help identify why there's different behavior between Workflow Test and Chatbot implementation?

Thank you in advance for your help!

**Comment by rainchen** [comment]
hi @haruyo 

1. I'm not sure what has changed you made since the the changed codes was the original code in the repo.
	- https://github.com/rainchen/dify-tool-LongTermMemory/blob/main/LongTermMemory.yml#L656
	- https://github.com/rainchen/dify-tool-LongTermMemory/blob/main/LongTermMemory.yml#L690

2. Can you share the output of Add memory node?

**Comment by haruyo** [comment]
Hi, @rainchen 
Thank you for getting back to me.
First of all, it caused errors from the beginning. 
I just followed your video. Can I still use it in the cloud version?
I thought Dify changed something. I will make a video to show how I made it later. Thank you.

**Comment by haruyo** [comment]
Hi, @rainchen This is how I did
https://www.youtube.com/watch?v=FPTDokbGpng

Then my current situation is 
- I could fix the JSON error in the workflow
- But in the chatbot, there is still the error

as I wrote it in the first topic.

**Comment by rainchen** [comment]
@haruyo please click on "Workflow Process" and show the entire OUTPUT content of "LongTermMemory", so that I can evaluate what's wrong.
for example:
![Screenshot 2024-11-11 at 12 35 56](https://github.com/user-attachments/assets/be4dd38a-36d7-43d4-a40b-50a305ff4b04)

PS: don't expose the API KEY in public. You should remove it immediately after recorded video.

**Comment by haruyo** [comment]
Thank you for getting back to me. 
I have deleted the API key already of course. Thank you.

This comment is only for the original node on my end.

These are traces of the error.

Chatbot:
![Screenshot 2024-11-11 160502](https://github.com/user-attachments/assets/eccad8c3-b4de-423b-b7cd-bb808f8657a4)

![Screenshot 2024-11-11 160542](https://github.com/user-attachments/assets/2b392be0-5500-4923-a15f-191e491a930e)

Then I tried to run the workflow directly by putting 'I am Bee'
![Screenshot 2024-11-11 160726](https://github.com/user-attachments/assets/d5bfc34f-a390-4abc-bd83-9a718c81bb69)

Then it also showed the error.
![Screenshot 2024-11-11 160758](https://github.com/user-attachments/assets/91bb1eed-7db1-42a3-8cfe-27df8e1af4e8)

![Screenshot 2024-11-11 160816](https://github.com/user-attachments/assets/94977661-5177-4dcb-8ad9-8842fc674941)

**Comment by haruyo** [comment]
This comment is how I changed it to solve the JSON error.

When I changed two things, it worked fine when it comes to 'ADD MEMORY'

1. Changed the JSON 

`{"segments":[{"content":"{{#1719907179295.longterm_memory_content#}}","keywords":["{{#sys.user_id#}}"]}]}`

2. Changed AGENT PROMPT

> # Long-term Memory Capability
> 
> You possess long-term memory capabilities, maintaining an independent long-term memory space for each user you interact with. Below is an explanation of long-term memory capabilities:
> 
> There is a ""Long-term Memory Content Template"" that declares the attribute tags to be saved. When the user's input content is related to the attribute tags defined in the template, the system analyzes the user's input based on the semantic meaning of the attribute tags in the template, extracts the corresponding attribute tag values, and finally generates the content for the ""Long-term Memory Space"" according to the template format.
> 
> ## Long-term Memory Content Template
> 
> The following is the specific long-term memory content template, contained within the `<longterm_memory_template>` tag:
> 
> <longterm_memory_template>
> {{ longterm_memory_template }}
> </longterm_memory_template>
> 
> ## Long-term Memory Content Template Example
> 
> For example, if the ""Long-term Memory Content Template"" is set as:
> 
> ```
> <memoryspace user_id=""{{ user_id }}"">
> <UserInfo>
> 	<name>${user_name}</name>
> 	<age>${user_age}</age>
> 	<hobbies>${user_hobbies}</hobbies>
> </UserInfo>
> </memoryspace>
> ```
> 
> The defined attribute tags in this example are: `<name>`, `<age>`, `<hobbies>`
> 
> Examples of attribute tags corresponding to automatically extracted values are:
> 
> - The `<name>` attribute tag identifies name-related information through the word `name`.
> - The `<age>` attribute tag identifies age-related information through the word `age`.
> - The `<hobbies>` attribute tag identifies personal interests and hobbies-related information through the word `hobbies`.
> 
> Examples of extracting attribute tag values:
> 
> - For instance, if the user input is `I'm Tom` or `my name is Tom`, the analysis reveals that the user's name is `Tom`, so the value of the `<name>` attribute tag is `Tom`.
> - If the user input is `I'm 30`, the analysis shows that the user's age is `30`, so the value of the `<age>` attribute tag is `30`.
> - If the user input is `I like reading`, the analysis indicates that the user's hobby is `reading`, so the value of the `<hobbies>` attribute tag is `reading`.
> 
> Thus, in this example, the final ""Long-term Memory Space"" content generated would be:
> 
> ```
> <memoryspace user_id=""{{ user_id }}"">
> <UserInfo>
> 	<name>Tom</name>
> 	<age>30</age>
> 	<hobbies>reading</hobbies>
> </UserInfo>
> <memoryspace>
> ```
> 
> ## Long-term Memory Space
> 
> The content of the long-term memory space is contained within the `<longterm_memory_space></longterm_memory_space>` tags:
> 
> <longterm_memory_space>
> {{ longterm_memory_space }}
> </longterm_memory_space>
> 
> ## Parameter Extraction
> 
> ### Extracting the `action` Parameter
> 
> The following are the conditions for the `action` parameter values (based on the `Long-term Memory Content Template` and the `Long-term Memory Content Template Example`):
> 
> - `add_user_memory`:
>   When the `input_text` mentions information related to the attribute tags defined in the `Long-term Memory Content Template`, and the `<longterm_memory_space></longterm_memory_space>` tags are **empty**.
> - `update_user_memory`:
>   When the `input_text` mentions information related to the attribute tags defined in the `Long-term Memory Content Template`, and the `<longterm_memory_space></longterm_memory_space>` tags are **not empty**.
> - `reply`:
>   When the `input_text` is **unrelated** to the attribute tags defined in the `Long-term Memory Content Template`.
> 
> ### Extracting the `longterm_memory_content` Parameter
> 
> When the `action` parameter value is not `reply`, refer to the examples described in the `Long-term Memory Content Template Example`, use the template defined in the `Long-term Memory Content Template`, analyze the user's input, combine it with the existing information in the ""Long-term Memory Space"", extract the values of the attribute tags to generate new ""Long-term Memory Space"" content. 
> 
> IMPORTANT: The output must be in XML format with special characters properly escaped for use in JSON strings. Each double quote ("") must be escaped with THREE backslashes (\\\""). For example:
> 
> <memoryspace user_id=\\\""[user_id]\\\""><UserInfo><name>Tom</name></UserInfo></memoryspace>
> 
> The above example shows how double quotes must be escaped: user_id=\\\""[user_id]\\\""
> 
> Do not include line breaks in the output. All double quotes in the XML must be escaped with \\\"" (three backslashes) to be valid in JSON.


![Screenshot 2024-11-11 161032](https://github.com/user-attachments/assets/aa5f0049-535d-4bf4-95c9-04f44b5a27f3)

**Comment by haruyo** [comment]
Then, after I fix the JSON error in the workflow,
I tested it in the Chatbot.
But it still showed the error.
![Screenshot 2024-11-11 163144](https://github.com/user-attachments/assets/162ea764-cf3b-45b6-91ce-c6e4d5e9de62)
![Screenshot 2024-11-11 163207](https://github.com/user-attachments/assets/dc46da8b-5bbc-48c6-b70e-aabb2a59ca4c)

Now I don't know how to debug it because we can't check the workflow trace when we use the chatbot.
Thank you so much

**Comment by rainchen** [comment]
To share the useful information for helping debugging the node:
In the Workflow Test Run view, click "TRACING" tab, click "LLM:Parameter Extractor" and "Action:add_memory" node , share the entire content of "PROCESS DATA" and "OUTPUT" content (copy and paste the content on GitHub with code block marks, not just a screenshot).

for example:
![Screenshot_2024-11-11_at_17_53_17](https://github.com/user-attachments/assets/4e75247c-e0c2-4aa1-b530-8359985d3a12)

the expected output of `LLM:Parameter Extractor` node should be like:

```
{
  "__is_success": 1,
  "__reason": null,
  "action": "add_user_memory",
  "longterm_memory_content": "<memoryspace user_id=\"bdf1fa0e-9b0e-46e6-ac74-a06da80853c6\"><UserInfo><name>Rain</name><age></age><hobbies></hobbies><any_user_info></any_user_info></UserInfo></memoryspace>"
}
```

PS:  remember to strip the `Authorization` part before sharing the content

**Comment by haruyo** [comment]
Hi, @rainchen 
Thank you. Do you need the original one?
1. I tested the original one and then got the error
2. I fixed its JSON error.
These are what I shared with you so far.

This time, I shared the data of no.1 ( Original one )

**The way of testing**
In the LLM: Parameter Extractor node, I put Run
Then I set 'INPUT' data. About the user_input,  it was 'I am Bee'

**LLM Parameter Extractor**
INPUT
```
{
  "query": "I am Bee",
  "files": [],
  "parameters": [
    {
      "name": "action",
      "type": "string",
      "options": null,
      "description": "action to take, should be one of: add_user_memory,update_user_memory,reply",
      "required": true
    },
    {
      "name": "longterm_memory_content",
      "type": "string",
      "options": null,
      "description": "longterm memory content",
      "required": false
    }
  ],
  "instruction": "{{#1719907030231.output#}}"
}
```

PROCESS DATA
```
{
  "model_mode": "chat",
  "prompts": [
    {
      "role": "system",
      "text": "You are a helpful assistant tasked with extracting structured information based on specific criteria provided. Follow the guidelines below to ensure consistency and accuracy.\n### Task\nAlways call the `extract_parameters` function with the correct parameters. Ensure that the information extraction is contextual and aligns with the provided criteria.\n### Memory\nHere is the chat history between the human and assistant, provided within <histories> tags:\n<histories>\n\n</histories>\n### Instructions:\nSome additional information is provided below. Always adhere to these instructions as closely as possible:\n<instruction>\n# Long-term Memory Capability\n\nYou possess long-term memory capabilities, maintaining an independent long-term memory space for each user you interact with. Below is an explanation of long-term memory capabilities:\n\nThere is a \"Long-term Memory Content Template\" that declares the attribute tags to be saved. When the user's input content is related to the attribute tags defined in the template, the system analyzes the user's input based on the semantic meaning of the attribute tags in the template, extracts the corresponding attribute tag values, and finally generates the content for the \"Long-term Memory Space\" according to the template format.\n\n## Long-term Memory Content Template\n\nThe following is the specific long-term memory content template, contained within the `<longterm_memory_template>` tag:\n\n<longterm_memory_template>\n<memoryspace user_id=\"c55d1e42-691e-4067-b4a5-fdd32bff52e5\">\n<UserInfo><name>${user_name}</name><age>${user_age}</age><hobbies>${user_hobbies}</hobbies><any_user_info>${any_user_info}</any_user_info></UserInfo>\n</memoryspace>\n</longterm_memory_template>\n\n## Long-term Memory Content Template Example\n\nFor example, if the \"Long-term Memory Content Template\" is set as:\n\n```\n<memoryspace user_id=\"c55d1e42-691e-4067-b4a5-fdd32bff52e5\">\n<UserInfo>\n\t<name>${user_name}</name>\n\t<age>${user_age}</age>\n\t<hobbies>${user_hobbies}</hobbies>\n</UserInfo>\n</memoryspace>\n```\n\nThe defined attribute tags in this example are: `<name>`, `<age>`, `<hobbies>`\n\nExamples of attribute tags corresponding to automatically extracted values are:\n\n- The `<name>` attribute tag identifies name-related information through the word `name`.\n- The `<age>` attribute tag identifies age-related information through the word `age`.\n- The `<hobbies>` attribute tag identifies personal interests and hobbies-related information through the word `hobbies`.\n\nExamples of extracting attribute tag values:\n\n- For instance, if the user input is `I'm Tom` or `my name is Tom`, the analysis reveals that the user's name is `Tom`, so the value of the `<name>` attribute tag is `Tom`.\n- If the user input is `I'm 30`, the analysis shows that the user's age is `30`, so the value of the `<age>` attribute tag is `30`.\n- If the user input is `I like reading`, the analysis indicates that the user's hobby is `reading`, so the value of the `<hobbies>` attribute tag is `reading`.\n\nThus, in this example, the final \"Long-term Memory Space\" content generated would be:\n\n```\n<memoryspace user_id=\"c55d1e42-691e-4067-b4a5-fdd32bff52e5\">\n<UserInfo>\n\t<name>Tom</name>\n\t<age>30</age>\n\t<hobbies>reading</hobbies>\n</UserInfo>\n<memoryspace>\n```\n\n## Long-term Memory Space\n\nThe content of the long-term memory space is contained within the `<longterm_memory_space></longterm_memory_space>` tags:\n\n<longterm_memory_space>\n\n</longterm_memory_space>\n\n## Parameter Extraction\n\n### Extracting the `action` Parameter\n\nThe following are the conditions for the `action` parameter values (based on the `Long-term Memory Content Template` and the `Long-term Memory Content Template Example`):\n\n- `add_user_memory`:\n  When the `input_text` mentions information related to the attribute tags defined in the `Long-term Memory Content Template`, and the `<longterm_memory_space></longterm_memory_space>` tags are **empty**.\n- `update_user_memory`:\n  When the `input_text` mentions information related to the attribute tags defined in the `Long-term Memory Content Template`, and the `<longterm_memory_space></longterm_memory_space>` tags are **not empty**.\n- `reply`:\n  When the `input_text` is **unrelated** to the attribute tags defined in the `Long-term Memory Content Template`.\n\n### Extracting the `longterm_memory_content` Parameter\n\nWhen the `action` parameter value is not `reply`, refer to the examples described in the `Long-term Memory Content Template Example`, use the template defined in the `Long-term Memory Content Template`, analyze the user's input, combine it with the existing information in the \"Long-term Memory Space\", extract the values of the attribute tags to generate new \"Long-term Memory Space\" content (ensure the generated content structure is the same as described in the template and is in XML format), and finally convert the long-term memory content into a format suitable for use as a value in JSON key-value pairs (ensure illegal characters are escaped).\n\n</instruction>\nSteps:\n1. Review the chat history provided within the <histories> tags.\n2. Extract the relevant information based on the criteria given, output multiple values if there is multiple relevant information that match the criteria in the given text. \n3. Generate a well-formatted output using the defined functions and arguments.\n4. Use the `extract_parameter` function to create structured outputs with appropriate parameters.\n5. Do not include any XML tags in your output.\n### Example\nTo illustrate, if the task involves extracting a user's name and their request, your function call might look like this: Ensure your output follows a similar structure to examples.\n### Final Output\nProduce well-formatted function calls in json without XML tags, as shown in the example.\n",
      "files": []
    },
    {
      "role": "user",
      "text": "### Structure\nHere is the structure of the JSON object, you should always follow the structure.\n<structure>\n{\"type\": \"object\", \"properties\": {\"location\": {\"type\": \"string\", \"description\": \"The location to get the weather information\", \"required\": true}}, \"required\": [\"location\"]}\n</structure>\n\n### Text to be converted to JSON\nInside <text></text> XML tags, there is a text that you should convert to a JSON object.\n<text>\nWhat is the weather today in SF?\n</text>\n",
      "files": []
    },
    {
      "role": "assistant",
      "text": "{\"location\": \"San Francisco\"}",
      "files": []
    },
    {
      "role": "user",
      "text": "### Structure\nHere is the structure of the JSON object, you should always follow the structure.\n<structure>\n{\"type\": \"object\", \"properties\": {\"food\": {\"type\": \"string\", \"description\": \"The food to eat\", \"required\": true}}, \"required\": [\"food\"]}\n</structure>\n\n### Text to be converted to JSON\nInside <text></text> XML tags, there is a text that you should convert to a JSON object.\n<text>\nI want to eat some apple pie.\n</text>\n",
      "files": []
    },
    {
      "role": "assistant",
      "text": "{\"result\": \"apple pie\"}",
      "files": []
    },
    {
      "role": "user",
      "text": "### Structure\nHere is the structure of the JSON object, you should always follow the structure.\n<structure>\n{\"type\": \"object\", \"properties\": {\"action\": {\"description\": \"action to take, should be one of: add_user_memory,update_user_memory,reply\", \"type\": \"string\"}, \"longterm_memory_content\": {\"description\": \"longterm memory content\", \"type\": \"string\"}}, \"required\": [\"action\"]}\n</structure>\n\n### Text to be converted to JSON\nInside <text></text> XML tags, there is a text that you should convert to a JSON object.\n<text>\nI am Bee\n</text>\n",
      "files": []
    }
  ],
  "usage": {
    "prompt_tokens": 1649,
    "prompt_unit_price": "5.00",
    "prompt_price_unit": "0.000001",
    "prompt_price": "0.0082450",
    "completion_tokens": 86,
    "completion_unit_price": "15.00",
    "completion_price_unit": "0.000001",
    "completion_price": "0.0012900",
    "total_tokens": 1735,
    "total_price": "0.0095350",
    "currency": "USD",
    "latency": 1.6479866220615804
  },
  "function": {},
  "tool_call": null,
  "llm_text": "```json\n{\n  \"action\": \"add_user_memory\",\n  \"longterm_memory_content\": \"<memoryspace user_id=\\\"c55d1e42-691e-4067-b4a5-fdd32bff52e5\\\"><UserInfo><name>Bee</name><age></age><hobbies></hobbies><any_user_info></any_user_info></UserInfo></memoryspace>\"\n}\n```"
}
```

OUTPUT
```
{
  "__is_success": 1,
  "__reason": null,
  "action": "add_user_memory",
  "longterm_memory_content": "<memoryspace user_id=\"c55d1e42-691e-4067-b4a5-fdd32bff52e5\"><UserInfo><name>Bee</name><age></age><hobbies></hobbies><any_user_info></any_user_info></UserInfo></memoryspace>"
}
```

**ACTION:ADD_MEMORY**
It showed only an error. There was no INPUT/OUTPUT field in TRACING
```
Expecting ',' delimiter: line 1 column 50 (char 49)
```

Thank you so much.

**Comment by lucaseatp** [comment]
same problem! I fixed the add/update modules adding a code node before it with a code to clean the json. but even if it runs perfectly on workflow as a tool, it doesn't work in a real chatflow! Randomly, it works, but about 15-20% of the time with the same configs. It's so weird since, on workflow, it works 100% of the time.

**Comment by lucaseatp** [comment]
lol, I just realized (2 minutes later) that saving doesn't do the trick. You needed to publish the workflow as a tool AGAIN. now it works like a charm lol

**Comment by lucaseatp** [comment]
lol, I just realized (2 minutes later) that saving doesn't do the trick. You have to publish the workflow as a tool AGAIN. now it works like a charm lol

**Comment by haruyo** [comment]
@lucaseatp Hi, wow!!! Finally, it worked. 
Thank you so much.
After fixing the JSON issue in the workflow, `Update` was not enough.
We had to click 'configure' to publish it as a workflow again. 

@rainchen Thank you for your help, now it's fine.
